### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by pedrokost** [thefrontside/emberx-select#1]
I installed the addon, but when I run the server I get the following error:

```
❯ ember s                                                                                 ✱
version: 0.2.0-beta.1
Could not find watchman, falling back to NodeWatcher for file system events
Livereload server on port 35729
Serving on http://0.0.0.0:4200/floorplan-editor/
File: emberx-select/components/x-select
Unexpected token (84:2)
SyntaxError: Unexpected token (84:2)
    at raise (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:333:15)
    at unexpected (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1366:5)
    at expect (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1360:18)
    at parseObj (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2203:9)
    at parseExprAtom (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2136:14)
    at parseExprSubscripts (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2012:28)
    at parseMaybeUnary (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1995:16)
    at parseExprOps (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1946:24)
    at parseMaybeConditional (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1930:16)
    at parseMaybeAssign (/home/pedro/Finesce/code/floorplan_editor/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1913:16)
```

Note that I am using ember-cli 0.2.0.beta.1 which has changed a few things about addons. It might be related.

**Comment by cowboyd** [comment]
@pedrokost This is fixed in 1.0.1 Apologies for the inconvenience.
