### ISSUE TITLE
Deprecation in 1.13.8

### ISSUE THREAD

**Issue by mike-post** [thefrontside/emberx-select#66]
I just upgraded to ember 1.13.8 and I'm seeing the following deprecation notice from emberx-select:

````
DEPRECATION: A property of <crawler-ui@view:-outlet::ember453> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation.
        at _emberViewsViewsCore_view.default.extend.scheduleRevalidate (http://localhost:4200/crawler/assets/vendor.js:60027:34)
        at http://localhost:4200/crawler/assets/vendor.js:22220:32
        at Object.Stream.notifySubscribers (http://localhost:4200/crawler/assets/vendor.js:31572:11)
        at Object.Stream.notifyExcept (http://localhost:4200/crawler/assets/vendor.js:31512:14)
        at Object.Stream.notify (http://localhost:4200/crawler/assets/vendor.js:31506:12)
        at Object.apply (http://localhost:4200/crawler/assets/vendor.js:32915:18)
        at Object.sendEvent (http://localhost:4200/crawler/assets/vendor.js:26465:28)
        at notifyObservers (http://localhost:4200/crawler/assets/vendor.js:30002:25)
        at propertyDidChange (http://localhost:4200/crawler/assets/vendor.js:29798:5)
````

I'm getting one deprecation notice for each option tag in the select.  My template is:
````
  {{#x-select value=daysFilter action="filterByDate"}}
    {{#each daysList as |day|}}
      {{#x-option value=day.value}}{{day.text}}{{/x-option}}
    {{/each}}
    {{#x-option value='custom' class=(if isStandardDate 'is-hidden')}}Custom range{{/x-option}}
  {{/x-select}}
````

I'm using the head of master, as recommended. I even tried `rm -rf node_modules ; npm cache clean ; npm install` to verify I was REALLY getting the latest, but no luck.

My package.son has `"emberx-select": "thefrontside/emberx-select",`

**Comment by nruth** [comment]
I'm seeing the same thing

**Comment by Robdel12** [comment]
Interesting. I'll try to take a look tonight. If not first thing tomorrow

**Comment by XpycT** [comment]
same thing

**Comment by Robdel12** [comment]
Sorry about that! We should be depreciation free now.

**Comment by mike-post** [comment]
Awesome, thank you!
